files:
  - source: /*.md
    translation: /%locale%/%file_name%.md
  - source: /README.md
    translation: /README.%locale_with_underscore%.md
  - source: /docs/**/*.md
    translation: /%locale%/docs/**/%file_name%.md

languages_mapping:
  locale:
    zh-CN: "zh-cn"
